USE [master]
GO

/****** Object:  Database [AdventureWorksLT2019]    Script Date: 7/2/2022 4:10:07 PM ******/
CREATE DATABASE [AdventureWorksLT2019]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorksLT2012_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2\MSSQL\DATA\AdventureWorksLT2012.mdf' , SIZE = 22464KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorksLT2012_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2\MSSQL\DATA\AdventureWorksLT2012_log.ldf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorksLT2019].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorksLT2019] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET ANSI_NULLS ON 
GO

ALTER DATABASE [AdventureWorksLT2019] SET ANSI_PADDING ON 
GO

ALTER DATABASE [AdventureWorksLT2019] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [AdventureWorksLT2019] SET ARITHABORT ON 
GO

ALTER DATABASE [AdventureWorksLT2019] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdventureWorksLT2019] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdventureWorksLT2019] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [AdventureWorksLT2019] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [AdventureWorksLT2019] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdventureWorksLT2019] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdventureWorksLT2019] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdventureWorksLT2019] SET  MULTI_USER 
GO

ALTER DATABASE [AdventureWorksLT2019] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdventureWorksLT2019] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdventureWorksLT2019] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdventureWorksLT2019] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdventureWorksLT2019] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdventureWorksLT2019] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AdventureWorksLT2019] SET QUERY_STORE = OFF
GO

USE [AdventureWorksLT2019]
GO

EXEC [AdventureWorksLT2019].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AdventureWorksLT 2012 Sample OLTP Database' 
GO

USE [master]
GO

ALTER DATABASE [AdventureWorksLT2019] SET  READ_WRITE 
GO

